## Combining things into an object 

### Adding Another Layer 

In [56]:
inputs = [[1 , 2, 3, 2.5 ],
         [2.0 , 5.0 , -1.0 , 2.0 ],
         [-1.5 , 2.7 , 3.3 , -0.8]] 


# Layer 1 : Having 3 neurons 

weights1 = [[0.2 , 0.8 , -0.5 , 1.0],
           [0.5 , -0.91 , 0.26 , -0.5],
           [-0.26 , -0.27 , 0.17 , 0.87]]

biases1 = [ 2 , 3, 0.5 ]


# Layer 2 : Having 3 neurons

weights2 = [[0.1 , -0.14 , 0.5],
           [-0.5 , 0.12 , -0.33],
           [-0.44 , 0.73 , -0.13]]

biases2 = [ -1 , 2, -0.5 ]



In [57]:
import numpy as np

layer1_output = np.dot(inputs , np.transpose(weights1)) + biases1
print( "Layer 1 output : \n",layer1_output)


## The output of previous layer acts as input for the next layer , 
##  This continues till output

layer2_output = np.dot ( layer1_output , np.transpose( weights2 )) + biases2

print( "Layer 2 output : \n",layer2_output)

Layer 1 output : 
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
Layer 2 output : 
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


### Creating Dense Layer Object 

In [68]:
from re import L
import numpy as np 
np.random.seed (0) 

class Layer_Dense :

    def __init__(self , input , neurons ):
        
        self.input = np.array ( input )

        # This line checks if the input contains one sameple, or more
        ## and then finds out the correct dimensions of inputs 
        
        features = self.input.shape[0] if len( self.input.shape) == 1 else self.input.shape[1]

        # generally dimensions of weights matrix = neurons * features, 
        # but we have to take transpose anyways, so we directly create neurons in dimension 
        self.weights = .01 * np.random.randn(  features , neurons )
        self.biases = .01 * np.zeros ( (1 , neurons) )

    def forward ( self ) :

        self.output = np.dot ( self.input , self.weights ) + self.biases 
         

In [ ]:
# Testing 
X = [[1 , 2, 3, 2.5 ],
     [2.0 , 5.0 , -1.0 , 2.0 ],
     [-1.5 , 2.7 , 3.3 , -0.8]] 


## Output from 1 layer acts as input for next layer, 
layer1 = Layer_Dense( X , 5 )
layer1.forward()
layer2 = Layer_Dense( layer1.output, 2 ) 
layer2.forward()

print( f"Layer1 Output : \n {layer1.output} \n",
      f"\nLayer2 Output :  \n {layer2.output} ")


Layer1 Output : 
 [[ 0.01075813  0.10398352  0.02446241  0.0318215   0.01885105]
 [-0.0083498   0.07084641  0.00029336  0.04470153  0.03636054]
 [-0.05076324  0.05568842  0.0079878  -0.03488957  0.00455304]] 
 
Layer2 Output :  
 [[ 0.00148296 -0.00083976]
 [ 0.00141003 -0.00013405]
 [ 0.0020125  -0.00072906]] 


In [64]:
# Example 2 (this time only with 1 input )
X2 = [1 , 2, 3, 2.5 ]

## Output from 1 layer acts as input for next layer, 
layer1 = Layer_Dense( X2 , 5 )
layer1.forward()
layer2 = Layer_Dense( layer1.output, 2 ) 
layer2.forward()

print( f"Layer1 Output : \n {layer1.output} \n",
      f"\nLayer2 Output :  \n {layer2.output} ")



Layer1 Output : 
 [-0.03060637 -0.04634218 -0.01188345 -0.0989637  -0.00091523] 
 
Layer2 Output :  
 [6.56411659e-05 1.18648432e-03] 


In [60]:
# Testing 
X = [[1 , 2, 3, 2.5 ],
     [2.0 , 5.0 , -1.0 , 2.0 ],
     [-1.5 , 2.7 , 3.3 , -0.8]] 

array = np.array( X )

features = array.shape[0] if len( array.shape) == 1 else array.shape[1]

weights = .01 * np.random.randn(  features , 5 )
biases = .01 * np.zeros (  5 )

output = np.dot ( array , weights ) + biases

output

array([[-0.03773199, -0.04553298, -0.01658111, -0.00937869, -0.03013325],
       [ 0.01264044,  0.05822206,  0.07497579, -0.11076798, -0.02123166],
       [-0.02920044, -0.00929282, -0.0167458 ,  0.09654089, -0.01806009]])

In [ ]:
biases = .01 * np.zeros ( (1, 5) )
biases .shape



(1, 5)